---
# ============================================================
# FortiGate Group Variables
# ============================================================

ansible_connection: httpapi
ansible_network_os: fortinet.fortios.fortios

ansible_httpapi_use_ssl: true
ansible_httpapi_validate_certs: false
ansible_httpapi_port: 443

firewall_vendor: fortinet
firewall_platform: fortios

fortigate_vdom: root

# ------------------------------------------------------------
# Secret reference
# ------------------------------------------------------------

fortigate_access_token: >-
  {{ vault_fortigate_access_tokens[inventory_hostname] }}

