---
all:
  children:

    firewalls:
      children:

        fortigates:
          hosts:

            fgt1:
              ansible_host: 192.168.100.101
              device_name: FGT1
              vendor: fortinet
              platform: fortios
              device_role: edge_firewall
              pod_id: 1

              management_interface: port1

              wan_interface: port2
              wan_addressing: dhcp

              transit_interface: port3
              transit_ip: 172.16.1.1/30
              transit_peer: pa6
              transit_peer_ip: 172.16.1.2

            fgt2:
              ansible_host: 192.168.100.102
              device_name: FGT2
              vendor: fortinet
              platform: fortios
              device_role: edge_firewall
              pod_id: 2

              management_interface: port1

              wan_interface: port2
              wan_addressing: dhcp

              transit_interface: port3
              transit_ip: 172.16.2.1/30
              transit_peer: pa7
              transit_peer_ip: 172.16.2.2

            fgt3:
              ansible_host: 192.168.100.103
              device_name: FGT3
              vendor: fortinet
              platform: fortios
              device_role: edge_firewall
              pod_id: 3

              management_interface: port1

              wan_interface: port2
              wan_addressing: dhcp

              transit_interface: port3
              transit_ip: 172.16.3.1/30
              transit_peer: pa8
              transit_peer_ip: 172.16.3.2

            fgt4:
              ansible_host: 192.168.100.104
              device_name: FGT4
              vendor: fortinet
              platform: fortios
              device_role: edge_firewall
              pod_id: 4

              management_interface: port1

              wan_interface: port2
              wan_addressing: dhcp

              transit_interface: port3
              transit_ip: 172.16.4.1/30
              transit_peer: pa9
              transit_peer_ip: 172.16.4.2

            fgt5:
              ansible_host: 192.168.100.105
              device_name: FGT5
              vendor: fortinet
              platform: fortios
              device_role: edge_firewall
              pod_id: 5

              management_interface: port1

              wan_interface: port2
              wan_addressing: dhcp

              transit_interface: port3
              transit_ip: 172.16.5.1/30
              transit_peer: pa10
              transit_peer_ip: 172.16.5.2


        paloaltos:
          hosts:

            pa6:
              ansible_host: 192.168.100.201
              device_name: PA6
              vendor: paloaltonetworks
              platform: panos
              device_role: internal_firewall
              pod_id: 1

              management_interface: mgmt

              transit_interface: ethernet1/1
              transit_ip: 172.16.1.2/30
              transit_peer: fgt1
              transit_peer_ip: 172.16.1.1

              lan_interface: ethernet1/2
              lan_gateway: 192.168.11.1/24
              lan_network: 192.168.11.0/24

              endpoint_name: Win27
              endpoint_ip: 192.168.11.10

            pa7:
              ansible_host: 192.168.100.202
              device_name: PA7
              vendor: paloaltonetworks
              platform: panos
              device_role: internal_firewall
              pod_id: 2

              management_interface: mgmt

              transit_interface: ethernet1/1
              transit_ip: 172.16.2.2/30
              transit_peer: fgt2
              transit_peer_ip: 172.16.2.1

              lan_interface: ethernet1/2
              lan_gateway: 192.168.12.1/24
              lan_network: 192.168.12.0/24

              endpoint_name: Win28
              endpoint_ip: 192.168.12.10

            pa8:
              ansible_host: 192.168.100.203
              device_name: PA8
              vendor: paloaltonetworks
              platform: panos
              device_role: internal_firewall
              pod_id: 3

              management_interface: mgmt

              transit_interface: ethernet1/1
              transit_ip: 172.16.3.2/30
              transit_peer: fgt3
              transit_peer_ip: 172.16.3.1

              lan_interface: ethernet1/2
              lan_gateway: 192.168.13.1/24
              lan_network: 192.168.13.0/24

              endpoint_name: Win30
              endpoint_ip: 192.168.13.10

            pa9:
              ansible_host: 192.168.100.204
              device_name: PA9
              vendor: paloaltonetworks
              platform: panos
              device_role: internal_firewall
              pod_id: 4

              management_interface: mgmt

              transit_interface: ethernet1/1
              transit_ip: 172.16.4.2/30
              transit_peer: fgt4
              transit_peer_ip: 172.16.4.1

              lan_interface: ethernet1/2
              lan_gateway: 192.168.14.1/24
              lan_network: 192.168.14.0/24

              endpoint_name: Win29
              endpoint_ip: 192.168.14.10

            pa10:
              ansible_host: 192.168.100.205
              device_name: PA10
              vendor: paloaltonetworks
              platform: panos
              device_role: internal_firewall
              pod_id: 5

              management_interface: mgmt

              transit_interface: ethernet1/1
              transit_ip: 172.16.5.2/30
              transit_peer: fgt5
              transit_peer_ip: 172.16.5.1

              lan_interface: ethernet1/2
              lan_gateway: 192.168.15.1/24
              lan_network: 192.168.15.0/24

              endpoint_name: Win31
              endpoint_ip: 192.168.15.10
